[providers.main]
recipients = ["age1p3frxn42yjgufrgrua4scy9z3wxddwqdsjm0glal5gem3rqg3fcqfvy78n"]
type = "age"

[secrets]
SECRET_TEXT = {provider = "main", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc3lnREJqSkRyNDU0bkhUNzM1c1U3bDYzeVYrQnpTZmVWSW5wRGJLVGtBCng2aU9kWU5MNWJYS0cxK2xVbjhpSG0zT0JnSDNSVFlkTFk2ZmF3VTdjWjgKLT4gZGBVJC1ncmVhc2UgUyZ9bCVXKGYKRTd3RVhISE1Tbm5RWHIydGZaN0haV3ErYUF1dWMrWk11S2UxRkFuYjZQU2ttMW9SNDdtbkluSS85WDExRmppSwpWb1IwT1E3ZTI3MkVmV2JzeWFhaEJSWHoKLS0tIFRaTXBEVU5CTUlaaEZQZ1BLeDFzY0FXMlRyZVFVb3IydnJQa1cxazgzMEUKzzVcPDsQpNOM2u1b8OPB9fEcEKr5xGeb/Pq7HqBK0PaRM/lvWab9d1WBqNhlMhWx9tE1ZCiZ"}
